import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Card from '../components/Card';

export default function Home() {
	return (
		<div>
			<Head>
				<title>favorishoes</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen flex items-center justify-center ">
				<Card>
					<Image src="/shoe.jpg" alt="shoe" width={300} height={300} />
				</Card>
			</main>
			<footer className="h-16 w-full bg-black sticky bottom-0 text-red-400">
				<button className="px-3 py2 m-4 bg-gray-900 rounded-full border-2 border-red-700">add</button>
			</footer>
		</div>
	);
}
